/** Small "AI" marker so users know a result was generated by AI. */
export function AiLabel() {
  return (
    <span className="rounded-md bg-gradient-to-r from-brand-blue to-brand-violet px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-wider text-white">
      AI
    </span>
  )
}
