using SkillHireAI.API.Middleware;

namespace SkillHireAI.API.Services;

public interface IResumeStorage
{
    /// <summary>Validates and saves the file. Returns the generated name on disk.</summary>
    Task<string> SaveAsync(IFormFile file);

    /// <summary>Opens a stored resume, or returns null if the file is missing.</summary>
    ResumeFile? Open(string storedName, string downloadName);

    void Delete(string? storedName);
}

public record ResumeFile(Stream Content, string ContentType, string FileName);

/// <summary>
/// Saves resumes to a private folder (not wwwroot), so they can only be
/// downloaded through endpoints that check who is asking.
/// </summary>
public class ResumeStorage : IResumeStorage
{
    public const long MaxBytes = 5 * 1024 * 1024;

    private static readonly Dictionary<string, (string ContentType, byte[] Signature)> AllowedTypes = new()
    {
        [".pdf"] = ("application/pdf", "%PDF"u8.ToArray()),
        [".docx"] = ("application/vnd.openxmlformats-officedocument.wordprocessingml.document", [0x50, 0x4B, 0x03, 0x04]),
        [".doc"] = ("application/msword", [0xD0, 0xCF, 0x11, 0xE0, 0xA1, 0xB1, 0x1A, 0xE1])
    };

    private readonly string _folder;

    public ResumeStorage(IConfiguration config, IWebHostEnvironment env)
    {
        var configured = config["Storage:ResumeFolder"] ?? "App_Data/resumes";
        _folder = Path.GetFullPath(Path.Combine(env.ContentRootPath, configured));
        Directory.CreateDirectory(_folder);
    }

    public async Task<string> SaveAsync(IFormFile file)
    {
        await ValidateAsync(file, AllowedTypes.Keys, "Only PDF, DOC and DOCX files are allowed.");

        var extension = Path.GetExtension(file.FileName).ToLowerInvariant();
        var storedName = $"{Guid.NewGuid():N}{extension}";
        await using var output = File.Create(GetPath(storedName));
        await file.CopyToAsync(output);

        return storedName;
    }

    /// <summary>
    /// Checks size, extension and the file's first bytes. Also used by the resume analyzer,
    /// which only accepts PDFs.
    /// </summary>
    public static async Task ValidateAsync(IFormFile file, IEnumerable<string> allowedExtensions, string wrongTypeMessage)
    {
        if (file.Length == 0)
        {
            throw new AppException("The selected file is empty.");
        }

        if (file.Length > MaxBytes)
        {
            throw new AppException("Resume must be 5 MB or smaller.");
        }

        var extension = Path.GetExtension(file.FileName).ToLowerInvariant();
        if (!allowedExtensions.Contains(extension) || !AllowedTypes.TryGetValue(extension, out var type))
        {
            throw new AppException(wrongTypeMessage);
        }

        // Check the file's first bytes so a renamed .exe can't pass as a .pdf.
        await using var check = file.OpenReadStream();
        var header = new byte[type.Signature.Length];
        var read = await check.ReadAtLeastAsync(header, header.Length, throwOnEndOfStream: false);
        if (read < header.Length || !header.AsSpan().SequenceEqual(type.Signature))
        {
            throw new AppException($"The file content does not look like a valid {extension} file.");
        }
    }

    public ResumeFile? Open(string storedName, string downloadName)
    {
        var path = GetPath(storedName);
        if (!File.Exists(path))
        {
            return null;
        }

        var extension = Path.GetExtension(storedName).ToLowerInvariant();
        var contentType = AllowedTypes.TryGetValue(extension, out var type) ? type.ContentType : "application/octet-stream";
        return new ResumeFile(File.OpenRead(path), contentType, downloadName);
    }

    public void Delete(string? storedName)
    {
        if (string.IsNullOrEmpty(storedName))
        {
            return;
        }

        var path = GetPath(storedName);
        if (File.Exists(path))
        {
            File.Delete(path);
        }
    }

    // Stored names are generated by us, but strip any path parts anyway so a
    // bad value can never point outside the resume folder.
    private string GetPath(string storedName) => Path.Combine(_folder, Path.GetFileName(storedName));
}
